import numpy as np
import matplotlib.pyplot as plt

# Loading data
sunx, suny, sunz, sunvx, sunvy, sunvz = np.loadtxt('sun_data.txt', unpack=True)
merx, mery, merz, mervx, mervy, mervz, merOrbRad = np.loadtxt('mercury_data.txt', unpack=True)
venx, veny, venz, venvx, venvy, venvz, venOrbRad = np.loadtxt('venus_data.txt', unpack=True)
earx, eary, earz, earvx, earvy, earvz, earOrbRad = np.loadtxt('earth_data.txt', unpack=True)
marx, mary, marz, marvx, marvy, marvz, marOrbRad = np.loadtxt('mars_data.txt', unpack=True)
jupx, jupy, jupz, jupvx, jupvy, jupvz, jupOrbRad = np.loadtxt('jupiter_data.txt', unpack=True)
satx, saty, satz, satvx, satvy, satvz, satOrbRad = np.loadtxt('saturn_data.txt', unpack=True)
uranx, uray, uraz, uravx, uravy, uravz, uraOrbRad = np.loadtxt('uranus_data.txt', unpack=True)
nepx, nepy, nepz, nepvx, nepvy, nepvz, nepOrbRad = np.loadtxt('neptune_data.txt', unpack=True)
Eerr, t = np.loadtxt('energy_error.txt', unpack=True)

fig, (ax_1, ax_2, ax_3) = plt.subplots(1, 3, figsize=(15,5), layout='tight')
ax_1.plot(sunx, suny)
ax_2.plot(merx, mery)
ax_3.plot(venx, veny)
ax_1.set_title('Sun Position')
ax_2.set_title('Mercury Position')
ax_3.set_title('Venus Position')
ax_1.set_xlabel('X Position (AU)')
ax_2.set_xlabel('X Position (AU)')
ax_3.set_xlabel('X Position (AU)')
ax_1.set_ylabel('Y Position (AU)')
ax_2.set_ylabel('Y Position (AU)')
ax_3.set_ylabel('Y Position (AU)')
plt.show()

fig, (ax_1, ax_2, ax_3) = plt.subplots(1, 3, figsize=(15,5), layout='tight')
ax_1.plot(earx, eary)
ax_2.plot(marx, mary)
ax_3.plot(jupx, jupy)
ax_1.set_title('Earth Position')
ax_2.set_title('Mars Position')
ax_3.set_title('Jupiter Position')
ax_1.set_xlabel('X Position (AU)')
ax_2.set_xlabel('X Position (AU)')
ax_3.set_xlabel('X Position (AU)')
ax_1.set_ylabel('Y Position (AU)')
ax_2.set_ylabel('Y Position (AU)')
ax_3.set_ylabel('Y Position (AU)')
plt.show()

fig, (ax_1, ax_2, ax_3) = plt.subplots(1, 3, figsize=(15,5), layout='tight')
ax_1.plot(satx, saty)
ax_2.plot(urax, uray)
ax_3.plot(nepx, nepy)
ax_1.set_title('Saturn Position')
ax_2.set_title('Uranus Position')
ax_3.set_title('Neptune Position')
ax_1.set_xlabel('X Position (AU)')
ax_2.set_xlabel('X Position (AU)')
ax_3.set_xlabel('X Position (AU)')
ax_1.set_ylabel('Y Position (AU)')
ax_2.set_ylabel('Y Position (AU)')
ax_3.set_ylabel('Y Position (AU)')
plt.show()

fig, (ax_1, ax_2) = plt.subplots(1, 2, figsize=(10,5), layout='tight')
ax_1.plot(t, merOrbRad)
ax_2.plot(t, venOrbRad)
ax_1.set_title('Mercury Orbital Radius')
ax_2.set_title('Venus Orbital Radius')
ax_1.set_xlabel('Time (N-body Units)')
ax_2.set_xlabel('Time (N-body Units)')
ax_1.set_ylabel('Orbital Radius (AU)')
ax_2.set_ylabel('Orbital Radius (AU)')
plt.show()

fig, (ax_1, ax_2) = plt.subplots(1, 2, figsize=(10,5), layout='tight')
ax_1.plot(t, earOrbRad)
ax_2.plot(t, marOrbRad)
ax_1.set_title('Earth Orbital Radius')
ax_2.set_title('Mars Orbital Radius')
ax_1.set_xlabel('Time (N-body Units)')
ax_2.set_xlabel('Time (N-body Units)')
ax_1.set_ylabel('Orbital Radius (AU)')
ax_2.set_ylabel('Orbital Radius (AU)')
plt.show()

fig, (ax_1, ax_2) = plt.subplots(1, 2, figsize=(10,5), layout='tight')
ax_1.plot(t, jupOrbRad)
ax_2.plot(t, satOrbRad)
ax_1.set_title('Jupiter Orbital Radius')
ax_2.set_title('Saturn Orbital Radius')
ax_1.set_xlabel('Time (N-body Units)')
ax_2.set_xlabel('Time (N-body Units)')
ax_1.set_ylabel('Orbital Radius (AU)')
ax_2.set_ylabel('Orbital Radius (AU)')
plt.show()

fig, (ax_1, ax_2) = plt.subplots(1, 2, figsize=(10,5), layout='tight')
ax_1.plot(t, uraOrbRad)
ax_2.plot(t, nepOrbRad)
ax_1.set_title('Uranus Orbital Radius')
ax_2.set_title('Neptune Orbital Radius')
ax_1.set_xlabel('Time (N-body Units)')
ax_2.set_xlabel('Time (N-body Units)')
ax_1.set_ylabel('Orbital Radius (AU)')
ax_2.set_ylabel('Orbital Radius (AU)')
plt.show()

plt.plot(t, Eerr)
plt.title('Energy Error')
plt.xlabel('Time (N-body Units)')
plt.ylabel('Energy Error')
plt.show()
